---
title: "Gestion pesquera desde el punto  de vista empresarial"
author: "Dr. Unai Ganzedo Lopez ss"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  slidy_presentation:
    footer: "Marine Support"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Diagrama Stakeholders
```{r setup2, , fig.pos='ht', echo=FALSE, out.width='100%',fig.align='center',fig.cap='Diagrama Stakeholders'}

suppressWarnings(suppressMessages(library(  DiagrammeR,warn.conflicts = FALSE, verbose =  F)))

grViz("
digraph dot {

    
graph [layout = dot, label='',fontsize =300,labelloc = t]

node [shape = circle,
      style = filled,
      color = grey,
      label = '']

node [fillcolor = green]
a[label='Sostenibilidad',fontsize =200, width = 10]

node [fillcolor = orange, width = 10,fontsize =100]
b[label='Gestión Pesquera'] c[label='Clientes'] d[label='Sector extractivo']

node [fillcolor = yellow , width = 10,fontsize =100]

edge [color = grey,dir=both ,arrowsize = 3,minlen = 10, color = Black]
a -> {b c d}
b -> {e[label='Organismos oficiales'] f[label='ONGs'] g[label='Certificación']}
c -> {k[label='Exigencia'] l[label='Disponibilidad'] m[label='Concienciación'] }
d -> {q[label='Visión de futuro'] r[label='Concienciación'] s[label='Sensibilidad']}
}")
```



## ¿Qué quiere el cliente ?

```{r setup3, , fig.pos='ht', echo=FALSE, out.width='100%',fig.align='center',fig.cap='El interés como clientes'}

suppressWarnings(suppressMessages(library(  DiagrammeR,warn.conflicts = FALSE, verbose =  F)))

grViz("
digraph dot {

    
graph [layout = dot, label='',fontsize =300,labelloc = t]

node [shape = circle,
      style = filled,
      color = grey,
      label = '']

node [fillcolor = green]

a[label='Cliente',fontsize =200, width = 10]
node [fillcolor = orange, width = 10,fontsize =100]

b[label='Sostenibilidad'] c[label='Calidad'] d[label='Precio']
node [fillcolor = yellow , width = 10,fontsize =100]

edge [color = grey,dir=both ,arrowsize = 3,minlen = 10, color = Black]



a -> {b c d}
b -> {e[label='Ecológica'] f[label='Social'] g[label='Visión de futuro']}
c -> {k[label='Alimentaria']  m[label='Seguridad'] }
d -> {q[label='Interés'] r[label='Preocupación'] s[label='Sensibilidad']}


}")
```



## ¿Qué quiere al armador?

```{r setup4, , fig.pos='ht', echo=FALSE, out.width='100%',fig.align='center',fig.cap='El interés como armador'}

suppressWarnings(suppressMessages(library(  DiagrammeR,warn.conflicts = FALSE, verbose =  F)))

grViz("
digraph dot {

    
graph [layout = dot, label='',fontsize =300,labelloc = t]

node [shape = circle,
      style = filled,
      color = grey,
      label = '']

node [fillcolor = green]

a[label='Armador',fontsize =200, width = 10]
node [fillcolor = orange, width = 10,fontsize =100]

b[label='Rentabilidad'] c[label='Estabilidad'] d[label='Imagen']
node [fillcolor = yellow , width = 10,fontsize =100]

edge [color = grey,dir=both ,arrowsize = 3,minlen = 10, color = Black]



a -> {b c d}
b -> {e[label='Buen Precio'] f[label='Menos costos'] }
c -> {k[label='Tranquilidad']  m[label='Durabilidad'] }
d -> {q[label='Prestigio'] r[label='Competitividad'] }


}")
```


## ¿Qué quieren los gestores?

```{r setup5, , fig.pos='ht', echo=FALSE, out.width='100%',fig.align='center',fig.cap='El interés como gestor'}

suppressWarnings(suppressMessages(library(  DiagrammeR,warn.conflicts = FALSE, verbose =  F)))

grViz("
digraph dot {

    
graph [layout = dot, label='',fontsize =300,labelloc = t]

node [shape = circle,
      style = filled,
      color = grey,
      label = '']

node [fillcolor = green]

a[label='Gestores',fontsize =200, width = 10]
node [fillcolor = orange, width = 10,fontsize =100]

b[label='Economía'] c[label='Ecología'] d[label='Justicia Social']
node [fillcolor = yellow , width = 10,fontsize =100]

edge [color = grey,dir=both ,arrowsize = 3,minlen = 10, color = Black]



a -> {b c d}
b -> {e[label='Directo'] f[label='Indirecto'] }
c -> {k[label='Sostenibilidad']   }
d -> {q[label='Paises'] r[label='Banderas'] m[label='Artes de pesca']}


}")
```
## Slide2 with R Output

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

